from pathlib import Path

tech_colors = {
    "AC": "#70af1d",
    "DC": "#8a1caf",
    "solar": "#f9d002",
    "onwind": "#235ebc",
    "hydro": "#298c81",
    "offwind-dc": "#74c6f2",
    "solar-hsat": "#fdb915",
    "offwind-ac": "#6895dd",
    "ror": "#3dbfb0",
    "PHS": "#51dbcc",
    "lignite": "#826837",
    "lignite (+CHP)": "#826837",
    "coal": "black",
    "coal (+CHP)": "black",
    "oil": "#c9c9c9",
    "uranium": "#ff8c00",
    "none": "",
    "co2": "#f29dae",
    "co2 stored": "#f2385a",
    "co2 sequestered": "#f2682f",
    "gas": "#e0986c",
    "H2": "#bf13a0",
    "battery": "fuchsia",
    "EV battery": "#baf238",
    "urban central heat": "#d15959",
    "urban central water tanks": "#e9977d",
    "urban central solar thermal": "#d7b24c",
    "biogas": "#e3d37d",
    "solid biomass": "#baa741",
    "biomass (+CHP)": "#baa741",
    "methanol": "#FF7B00",
    "home battery": "#80c944",
    "unsustainable biogas": "",
    "unsustainable solid biomass": "#998622",
    "unsustainable bioliquids": "#32CD32",
    "H2 Store": "#bf13a0",
    "gas for industry CC": "#692e0a",
    "urban central air heat pump": "#6cfb6b",
    "battery discharger": "palegreen",
    "urban central resistive heater": "#8cdf85",
    "biomass to liquid CC": "#32DDD2",
    "urban central solid biomass CHP": "#9d9042",
    "battery charger": "#88a75b",
    "home battery discharger": "#3c5221",
    "H2 pipeline retrofitted": "#ba99b5",
    "DAC": "#ff5270",
    "solid biomass for industry CC": "#47411c",
    "land transport oil": "#afafaf",
    "BEV charger": "#baf238",
    "industry methanol": "#468c8b",
    "shipping oil": "#808080",
    "OCGT": "#e0986c",
    "urban central gas boiler": "#b0904f",
    "gas compressing": "#e05b09",
    "kerosene for aviation": "#a1ffe6",
    "HVC to air": "k",
    "SMR": "#870c71",
    "home battery charger": "#5e8032",
    "coal for industry": "#343434",
    "electricity distribution grid": "#97ad8c",
    "urban central water tanks discharger": "#b9816e",
    "urban central solid biomass CHP CC": "#6c5d28",
    "methanolisation": "#00FFBF",
    "biogas to gas": "#e36311",
    "waste CHP CC": "#e3d3ff",
    "Fischer-Tropsch": "#25c49a",
    "process emissions": "#222222",
    "biomass to liquid": "#32CD32",
    "biogas to gas CC": "#e51245",
    "waste CHP": "#e3d37d",
    "H2 pipeline": "#f081dc",
    "Sabatier": "#9850ad",
    "naphtha for industry": "#57ebc4",
    "agriculture machinery oil": "#949494",
    "H2 Fuel Cell": "#c251ae",
    "urban central gas CHP": "#8d5e56",
    "oil refining": "#a6a6a6",
    "solid biomass for industry": "#7a6d26",
    "SMR CC": "#4f1745",
    "H2 Electrolysis": "#ff29d9",
    "gas for industry": "#853403",
    "urban central gas CHP CC": "#6e4e4c",
    "urban central water tanks charger": "#b57a67",
    "process emissions CC": "#000000",
    "urban central heat vent": "#a74747",
    "oil primary": "#d2d2d2",
    "gas primary": "#e05b09",
    "solar rooftop": "#ffea80",
    "land transport EV": "#baf238",
    "industry electricity": "violet",
    "low-temperature heat for industry": "#8f2727",
    "H2 for industry": "#f073da",
    "agriculture heat": "#d9a5a5",
    "land transport fuel cell": "#6b3161",
    "electricity": "#110d63",
    "agriculture electricity": "#494778",
    "low voltage": "#97ad8c",
    "non-sequestered HVC": "",
    "rural air heat pump": "#5af95d",
    "rural biomass boiler": "#a1a066",
    "rural gas boiler": "#d4722e",
    "rural ground heat pump": "#48f74f",
    "rural heat": "#ff7c7c",
    "rural resistive heater": "#a5ed9d",
    "rural solar thermal": "#f1c069",
    "rural water tanks": "#f7b7a3",
    "rural water tanks charger": "#b3abb0",
    "rural water tanks discharger": "#ba9685",
    "urban decentral air heat pump": "#5af95d",
    "urban decentral biomass boiler": "#b0b87b",
    "urban decentral gas boiler": "#ba8947",
    "urban decentral heat": "#a33c3c",
    "urban decentral resistive heater": "#98e991",
    "urban decentral solar thermal": "#e5bc5a",
    "urban decentral water tanks": "#f2b2a3",
    "urban decentral water tanks charger": "#b3becc",
    "urban decentral water tanks discharger": "#baac9e",
    "urban central lignite CHP": "#f7a889",
    "urban central oil CHP": "#e26952",
    "urban decentral oil boiler": "",
    "urban central coal CHP": "#b40426",
    "rural oil boiler": "",
    "CCGT": "purple",
    "gas (+CHP)": "purple",
    "nuclear": "lime",
    "renewable oil": "",
    "renewable gas": "",
    "Other": "gray",
    "H2 OCGT": "#3b4cc0",
    "H2 pipeline (Kernnetz)": "#6788ee",
    "H2 retrofit OCGT": "#9abbff",
    "urban central H2 CHP": "#c9d7f0",
    "urban central H2 retrofit CHP": "#edd1c2",
    "interconnectors": "darkorange",
    "coal CHP": "#b40426",
    "H2 CHP": "pink",
    "H2 (+CHP)": "pink",
    "biomass CHP": "#9d9042",
    "Fuel Cell": "#c251ae",
    "import": "orchid",
    "export": "grey",
    "interconnectors supply": "orange",
    "interconnectors demand": "purple",
    "PHS charging": "darkgreen",
    "PHS discharging": "darkgreen",
    "heat pump": "red",
    "resistive heater": "khaki",
    "Import/Export": "dimgrey",
    "Sonstige": "gainsboro",
    "industry DSM": "navy",
    "industry DSM ramp down": "mediumslateblue",
    "industry DSM compensate": "cornflowerblue",
    "Onshore wind": "#235ebc",
    "Offshore wind": "#6788ee",
    "Solar": "#ffea80",
    "Gas": "navajowhite",
    "Gas CHP": "navajowhite",
    "Pumped storage": "#51dbcc",
    "Battery": "palegreen",
    "Power-to-heat": "crimson",
    "Electrolysis": "#ff29d9",
    "Others": "grey",
    "V2G": "tomato",
    "iron-air battery": '#f5e6b3',
    "iron-air battery storage": '#daa520',
    "iron-air battery charger": '#c9954d',
    "iron-air battery discharger": '#8b6f47'
}


year_colors_gradient = {
    2020: "#e4c1f9",  # Pale Lavender
    2025: "#c191c9",  # Soft Lilac
    2030: "#9c89b8",  # Lavender Purple
    2035: "#7b68ac",  # Muted Purple
    2040: "#5e4fa2",  # Deep Violet
    2045: "#3c096c",  # Intense Purple
    2050: "#240046",  # Dark Purple
}

# Technology grouping dictionary
tech_groups = {
    "gas (+CHP)": ["gas CHP", "OCGT", "CCGT"],
    "coal (+CHP)": ["coal", "lignite"],
    "oil (+CHP)": ["oil"],
    "waste (+CHP)": ["waste"],
    "H2 (+CHP)": ["H2 retrofit", "H2  CCGT", "H2 OCGT", "H2 CHP"],
    "biomass (+CHP)": ["biomass"],
    "heat pump": ["heat pump"],
    "resistive heater": ["resistive heater"],
    "industry DSM": ["industry DSM"],
    "interconnectors": [
        "AC",
        "DC",
        "import",
        "export",
        "electricity distribution grid losses",
    ],
}


def find_project_root():
    """Find project root by looking for .git or Snakefile."""
    current = Path(__file__).resolve().parent
    for parent in [current] + list(current.parents):
        if (parent / ".git").exists() or (parent / "Snakefile").exists():
            return parent
    return current.parent


# Scenario abbreviations dictionary
scenario_abbrev = {
    'LowFlex50': 'LF50',
    'LowFlex75': 'LF75',
    'LowBatt50': 'LB50',
    'LowBatt75': 'LB75',
    'LowBatt25': 'LB25',
    'MedFlex': 'MedF',
    'HigFlex': 'HigF',
    'LowTransmission110': 'LT10',
    'LowTransmission125': 'LT25',
    'LowPtX75': 'LX75',
    'LowPtX50': 'LX50',
    'LowPtX25': 'LX25',
    'LowH2Store75': 'LH75',
    'LowH2Store50': 'LH50',
    'LowH2Store25': 'LH25',
    'LowHeatStore75': 'HS75',
    'LowHeatStore50': 'HS50',
    'LowHeatStore25': 'HS25',
}
