# Define flexible technologies
flex_techs = {
    "no": "",
    "interconnectors": ["AC", "DC"],
    "coal": ["lignite", "coal"],
    "gas": ["OCGT", "CCGT"],
    "biogas": ["biogas"],
    "oil": ["oil"],
    "nuclear": ["nuclear"],
    "solid biomass": ["solid biomass"],
    "PHS": ["PHS"],
    "H2 OCGT": ["H2 OCGT", "H2 retrofit OCGT"],
    "battery": ["battery discharger"],
    "coal CHP": ["urban central coal CHP", "urban central lignite CHP"],
    "gas CHP": ["urban central gas CHP", "urban central gas CHP CC"],
    "H2 CHP": ["urban central H2 CHP", "urban central H2 retrofit CHP"],
    "biomass CHP": [
        "urban central solid biomass CHP",
        "urban central solid biomass CHP CC",
    ],
    "waste CHP": ["waste CHP", "waste CHP CC"],
    "hydro": ["hydro"],
    "Fuel Cell": ["H2 Fuel Cell"],
}

# Define flexible technologies
flex_techs_supply = {
    "no": "",
    "interconnectors supply": ["AC", "DC"],
    "import": ["import"],
    "coal": ["lignite", "coal"],
    "gas": ["OCGT", "CCGT"],
    "biogas": ["biogas"],
    "oil": ["oil"],
    "nuclear": ["nuclear"],
    "solid biomass": ["solid biomass"],
    "PHS discharging": ["PHS"],
    "H2 OCGT": ["H2 OCGT", "H2 retrofit OCGT"],
    "battery discharger": ["battery discharger", "home battery discharger"],
    "coal CHP": ["urban central coal CHP", "urban central lignite CHP"],
    "gas CHP": ["urban central gas CHP", "urban central gas CHP CC"],
    "H2 CHP": ["urban central H2 CHP", "urban central H2 retrofit CHP"],
    "biomass CHP": [
        "urban central solid biomass CHP",
        "urban central solid biomass CHP CC",
    ],
    "waste CHP": ["waste CHP", "waste CHP CC"],
    "hydro": ["hydro"],
    "Fuel Cell": ["H2 Fuel Cell"],
}

flex_techs_demand = {
    "interconnectors demand": ["AC", "DC"],
    "export": ["export"],
    "H2 Electrolysis": ["H2 Electrolysis"],
    "BEV charger": ["BEV charger"],
    "PHS charging": ["PHS"],
    "battery charger": ["battery charger", "home battery charger"],
    "heat pump": [
        "rural ground heat pump",
        "rural air heat pump",
        "urban decentral air heat pump",
        "urban central air heat pump",
    ],
    "resistive heater": [
        "rural resistive heater",
        "urban decentral resistive heater",
        "urban central resistive heater",
    ],
    "methanolisation": ["methanolisation"],
}

carriers_in_german = {
    "DC": "Gleichstrom",
    "AC": "Wechselstrom",
    "hydro": "Wasserkraft (Reservoir & Damm)",
    "offwind-ac": "Offshore-Wind (AC)",
    "offwind-dc": "Offshore-Wind (DC)",
    "solar": "Solar",
    "solar-hsat": "Solar (HSAT)",
    "onwind": "Onshore-Wind",
    "PHS": "Pumpspeicherkraftwerk",
    "ror": "Laufwasserkraft",
    "": "",
    "lignite": "Braunkohle",
    "coal": "Steinkohle",
    "oil": "Öl",
    "uranium": "Uran",
    "none": "keine",
    "co2": "CO2",
    "co2 stored": "CO2 gespeichert",
    "co2 sequestered": "CO2 sequestriert",
    "gas": "Gas",
    "H2": "Wasserstoffspeicher",
    "battery": "Batteriespeicher",
    "EV battery": "Elektrofahrzeug-Batterie",
    "urban central heat": "Zentrale städtische Heizung",
    "urban central water tanks": "Zentrale städtische Wassertanks",
    "urban central solar thermal": "Zentrale städtische Solarthermie",
    "biogas": "Biogas",
    "solid biomass": "Biomasse",
    "methanol": "Methanol",
    "home battery": "Hausbatterie",
    "rural heat": "Ländliche Wärme",
    "rural solar thermal": "Ländliche Solarthermie",
    "rural water tanks": "Ländliche Wassertanks",
    "urban decentral heat": "Dezentrale städtische Heizung",
    "urban decentral solar thermal": "Dezentrale städtische Solarthermie",
    "urban decentral water tanks": "Dezentrale städtische Wassertanks",
    "oil primary": "Primäröl",
    "solar rooftop": "Solar-Dach",
    "urban central heat vent": "Zentrale städtische Wärmeentlüftung",
    "gas primary": "Primärgas",
    "solid biomass for industry": "Biomasse (Industrie)",
    "shipping oil": "Schiffsöl",
    "agriculture machinery oil": "Landwirtschaftsmaschinenöl",
    "naphtha for industry": "Naphtha für die Industrie",
    "land transport oil": " Öl (Transport)",
    "kerosene for aviation": "Kerosin für die Luftfahrt",
    "non-sequestered HVC": "Nicht-sequestriertes HVC",
    "shipping methanol": "Methanol für Schifffahrt",
    "gas for industry": "Gas (Industrie)",
    "low voltage": "Niederspannung",
    "industry methanol": "Methanol (Industrie)",
    "coal for industry": "Kohle (Industrie)",
    "process emissions": "Prozessemissionen",
    "industry electricity": "Industrieelektrizität",
    "low-temperature heat for industry": "Niedertemperaturwärme (Industrie)",
    "agriculture electricity": "Landwirtschaftliche Elektrizität",
    "electricity": "Elektrizität",
    "land transport EV": "Elektrofahrzeuge (Transport)",
    "agriculture heat": "Landwirtschaftliche Wärme",
    "urban central air heat pump": "Zentrale städtische Luftwärmepumpe",
    "electricity distribution grid": "Stromverteilungsnetz",
    "battery charger": "Batterie Laden",
    "waste CHP": "Müll-KWK",
    "urban central water tanks discharger": "Entladung zentraler städtischer Wassertanks",
    "rural water tanks discharger": "Entladung ländlicher Wassertanks",
    "urban decentral biomass boiler": "Dezentrale städtische Biomassekessel",
    "BEV charger": "E-Fahrzeug Laden",
    "rural ground heat pump": "Erdwärmepumpe",
    "Fischer-Tropsch": "Fischer-Tropsch",
    "urban decentral water tanks discharger": "Entladung dezentraler städtischer Wassertanks",
    "urban central gas CHP": "Gas-KWK",
    "Sabatier": "Sabatier-Prozess",
    "gas compressing": "Gasverdichtung",
    "home battery charger": "Hausbatterie Laden",
    "battery discharger": "Batterie Entladung",
    "H2 pipeline retrofitted": "Nachgerüstete Wasserstoffpipeline",
    "rural resistive heater": "Ländlicher Widerstandsheizer",
    "urban central water tanks charger": "Ladung zentraler städtischer Wassertanks",
    "urban central solid biomass CHP CC": "Biomasse-KWK mit CO2-Abscheidung",
    "rural air heat pump": "Ländliche Luftwärmepumpe",
    "DAC": "Direkte CO2-Abscheidung",
    "urban decentral air heat pump": "Dezentrale städtische Luftwärmepumpe",
    "waste CHP CC": "Müll-KWK mit CO2-Abscheidung",
    "biomass to liquid CC": "Biomasse zu Flüssigkeit mit CO2-Abscheidung",
    "HVC to air": "HVC in die Luft",
    "methanolisation": "Methanolisation",
    "gas for industry CC": "Gas mit CO2-Abscheidung (Industrie)",
    "H2 pipeline": "Wasserstoffpipeline",
    "solid biomass for industry CC": "Biomasse mit CO2-Abscheidung (Industrie)",
    "urban decentral gas boiler": "Dezentrale städtische Gaskessel",
    "urban central gas CHP CC": "Gas-KWK mit CO2-Abscheidung",
    "rural gas boiler": "Ländlicher Gaskessel",
    "process emissions CC": "Prozessemissionen mit CO2-Abscheidung",
    "urban decentral water tanks charger": "Ladung dezentraler städtischer Wassertanks",
    "biogas to gas CC": "Biogas zu Gas mit CO2-Abscheidung",
    "urban decentral resistive heater": "Dezentrale städtische Widerstandsheizer",
    "biogas to gas": "Biogas zu Gas",
    "OCGT": "Gas (OCGT)",
    "urban central solid biomass CHP": "Biomasse-KWK",
    "urban central gas boiler": "Zentraler städtischer Gaskessel",
    "urban central resistive heater": "Zentraler städtischer Widerstandsheizer",
    "oil refining": "Ölraffinierung",
    "rural biomass boiler": "Ländlicher Biomassekessel",
    "SMR": "Dampfreformierung",
    "biomass to liquid": "Biomasse zu Flüssigkeit",
    "rural water tanks charger": "Ladung ländlicher Wassertanks",
    "home battery discharger": "Hausbatterie Entladung",
    "H2 Store": "Wasserstoffspeicher",
    "renewable oil": "Erneuerbares Öl",
    "renewable gas": "Erneuerbares Gas",
    "CCGT": "Gas (CCGT)",
    "nuclear": "Kernenergie",
    "gas CHP": "Gas-KWK",
    "gas CHP CC": "Gas KWK mit CO2-Abscheidung",
    "urban central coal CHP": "Steinkohle-KWK",
    "coal CHP": "Steinkohle-KWK",
    "Electricity trade": "Stromhandel",
    "urban central gas CHP": "Gas-KWK",
    "urban central biomass CHP": " Biomasse-KWK",
    "biomass CHP": "Biomasse-KWK",
    "air heat pump": "Luftwärmepumpe",
    "Electricity load": "Elektrizitätslast",
    "methanolisation": "Methanolisierung",
    "resistive heater": "Widerstandsheizer",
    "gas boiler": "Gaskessel",
    "H2 Electrolysis": "Elektrolyse",
    "H2 Fuel Cell": "Brennstoffzelle (Strom)",
    "H2 for industry": "H2 für Industrie",
    "H2 OCGT": "Wasserstoff (OCGT)",
    "H2 CHP": "H2 KWK",
    "land transport fuel cell": "Brennstoffzelle (Verkehr)",
    "other": "Sonstige",
    "SMR CC": "Dampfreformierung mit CCS",
    "H2 pipeline (new)": "H2 Pipeline (Neubau)",
    "H2 pipeline (repurposed)": "H2 Pipeline (Umstellung)",
    "H2 pipeline (Kernnetz)": "H2 Pipeline (Kernnetz)",
    "heat pump": "Wärmepumpe",
    "urban central H2 CHP": "Wasserstoff-KWK",
    "urban central H2 retrofit CHP": "Wasserstoff-KWK (Umrüstung)",
    "urban central oil CHP": "Öl-KWK",
    "urban central lignite CHP": "Braunkohle-KWK",
    "H2 retrofit OCGT": "Wasserstoff (OCGT;Umrüstung)",
}


tech_colors = {
    "AC": "#70af1d",
    "DC": "#8a1caf",
    "solar": "#f9d002",
    "onwind": "#235ebc",
    "hydro": "#298c81",
    "offwind-dc": "#74c6f2",
    "solar-hsat": "#fdb915",
    "offwind-ac": "#6895dd",
    "ror": "#3dbfb0",
    "PHS": "#51dbcc",
    "lignite": "#826837",
    "lignite (+CHP)": "#826837",
    "coal": "black",
    "coal (+CHP)": "black",
    "oil": "#c9c9c9",
    "uranium": "#ff8c00",
    "none": "",
    "co2": "#f29dae",
    "co2 stored": "#f2385a",
    "co2 sequestered": "#f2682f",
    "gas": "#e0986c",
    "H2": "#bf13a0",
    "battery": "fuchsia",
    "EV battery": "#baf238",
    "urban central heat": "#d15959",
    "urban central water tanks": "#e9977d",
    "urban central solar thermal": "#d7b24c",
    "biogas": "#e3d37d",
    "solid biomass": "#baa741",
    "biomass (+CHP)": "#baa741",
    "methanol": "#FF7B00",
    "home battery": "#80c944",
    "unsustainable biogas": "",
    "unsustainable solid biomass": "#998622",
    "unsustainable bioliquids": "#32CD32",
    "H2 Store": "#bf13a0",
    "gas for industry CC": "#692e0a",
    "urban central air heat pump": "#6cfb6b",
    "battery discharger": "palegreen",
    "urban central resistive heater": "#8cdf85",
    "biomass to liquid CC": "#32DDD2",
    "urban central solid biomass CHP": "#9d9042",
    "battery charger": "#88a75b",
    "home battery discharger": "#3c5221",
    "H2 pipeline retrofitted": "#ba99b5",
    "DAC": "#ff5270",
    "solid biomass for industry CC": "#47411c",
    "land transport oil": "#afafaf",
    "BEV charger": "#baf238",
    "industry methanol": "#468c8b",
    "shipping oil": "#808080",
    "OCGT": "navajowhite",
    "urban central gas boiler": "#b0904f",
    "gas compressing": "#e05b09",
    "kerosene for aviation": "#a1ffe6",
    "HVC to air": "khaki",
    "SMR": "#870c71",
    "home battery charger": "#5e8032",
    "coal for industry": "#343434",
    "electricity distribution grid": "#97ad8c",
    "urban central water tanks discharger": "#b9816e",
    "urban central solid biomass CHP CC": "#6c5d28",
    "methanolisation": "#00FFBF",
    "biogas to gas": "#e36311",
    "waste CHP CC": "#e3d3ff",
    "Fischer-Tropsch": "#25c49a",
    "process emissions": "#222222",
    "biomass to liquid": "#32CD32",
    "biogas to gas CC": "#e51245",
    "waste CHP": "#e3d37d",
    "H2 pipeline": "#f081dc",
    "Sabatier": "#9850ad",
    "naphtha for industry": "#57ebc4",
    "agriculture machinery oil": "#949494",
    "H2 Fuel Cell": "#c251ae",
    "urban central gas CHP": "#8d5e56",
    "oil refining": "#a6a6a6",
    "solid biomass for industry": "#7a6d26",
    "SMR CC": "#4f1745",
    "H2 Electrolysis": "#ff29d9",
    "gas for industry": "#853403",
    "urban central gas CHP CC": "#6e4e4c",
    "urban central water tanks charger": "#b57a67",
    "process emissions CC": "#000000",
    "urban central heat vent": "#a74747",
    "oil primary": "#d2d2d2",
    "gas primary": "#e05b09",
    "solar rooftop": "#ffea80",
    "land transport EV": "#baf238",
    "industry electricity": "#2d2a66",
    "low-temperature heat for industry": "#8f2727",
    "H2 for industry": "#f073da",
    "agriculture heat": "#d9a5a5",
    "land transport fuel cell": "#6b3161",
    "electricity": "#110d63",
    "agriculture electricity": "#494778",
    "low voltage": "#97ad8c",
    "non-sequestered HVC": "",
    "rural air heat pump": "#5af95d",
    "rural biomass boiler": "#a1a066",
    "rural gas boiler": "#d4722e",
    "rural ground heat pump": "#48f74f",
    "rural heat": "#ff7c7c",
    "rural resistive heater": "#a5ed9d",
    "rural solar thermal": "#f1c069",
    "rural water tanks": "#f7b7a3",
    "rural water tanks charger": "#b3abb0",
    "rural water tanks discharger": "#ba9685",
    "urban decentral air heat pump": "#5af95d",
    "urban decentral biomass boiler": "#b0b87b",
    "urban decentral gas boiler": "#ba8947",
    "urban decentral heat": "#a33c3c",
    "urban decentral resistive heater": "#98e991",
    "urban decentral solar thermal": "#e5bc5a",
    "urban decentral water tanks": "#f2b2a3",
    "urban decentral water tanks charger": "#b3becc",
    "urban decentral water tanks discharger": "#baac9e",
    "urban central lignite CHP": "#f7a889",
    "urban central oil CHP": "#e26952",
    "urban decentral oil boiler": "",
    "urban central coal CHP": "#b40426",
    "rural oil boiler": "",
    "CCGT": "purple",
    "gas (+CHP)": "purple",
    "nuclear": "lime",
    "renewable oil": "",
    "renewable gas": "",
    "Other": "gray",
    "H2 OCGT": "orchid",
    "H2 pipeline (Kernnetz)": "#6788ee",
    "H2 retrofit OCGT": "#9abbff",
    "urban central H2 CHP": "#c9d7f0",
    "urban central H2 retrofit CHP": "#edd1c2",
    "interconnectors": "darkorange",
    "coal CHP": "#b40426",
    "gas CHP": "#8d5e56",
    "H2 CHP": "pink",
    "biomass CHP": "#9d9042",
    "Fuel Cell": "#c251ae",
    "import": "orchid",
    "export": "grey",
    "interconnectors supply": "orange",
    "interconnectors demand": "purple",
    "PHS charging": "darkgreen",
    "PHS discharging": "darkgreen",
    "heat pump": "red",
    "resistive heater": "khaki",
    "Import/Export": "dimgrey",
    "Sonstige": "gainsboro",
}
